
services:
  postgres:
    image: postgres:latest
    container_name: event_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./src:/docker-entrypoint-initdb.d